version: "3.8"

services: 
    dotnet-five-sample-api:
        container_name: dotnet-five-sample-api
        build:
          context: .
          dockerfile: ./Dockerfile
        environment:
          ASPNETCORE_ENVIRONMENT: Release
        ports:
        - 8080:80